### ISSUE TITLE
[Question] Design pattern for services

### ISSUE THREAD

**Issue by olivierobert** [hudrucan/google-search-results-functions#8]
Throughout the codebase, there are signs that you focused on implementing SOLID patterns and several abstractions layers with DTOs, repositories, etc. However, when reviewing the services, that contain the code domain logic, these classes do not seem to adhere to strict patterns.

For instance, `ScraperService` handles both Google and Bing scrapping which violates the single responsibility principle. The constructor methods are not used while it would be better to use to make use of inversion to trigger either a Google or Bind scrapping. The actual scrapping logic for Google and Bing could be done in separate classes. 

Therefore, why opting for the current implementation? Is there anything that I miss that makes the current implementation better?

**Comment by hudrucan** [comment]
No, you right, I was implemented wrong the pattern on service classes. It's really better if I separate Google and Bing to different class.
